app:
  name: "belajar-golang-viper"
  author: "Wahyu Azizi"
  version: "1.0.0"

database:
  driverName: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  name: EduQueasy_db
